version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - misspell
    - unconvert
    - unparam
    - goconst
    - nakedret
    - prealloc
    - bodyclose

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    gocritic:
      disabled-checks:
        - ifElseChain

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - unparam

formatters:
  enable:
    - gofumpt
    - goimports
